package com.lexives.pokedex.view

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.snapshotFlow
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import coil3.compose.AsyncImage
import com.lexives.pokedex.domain.Pokemon
import com.lexives.pokedex.domain.PokemonSprites
import com.lexives.pokedex.domain.PokemonType
import com.lexives.pokedex.state.DataState
import com.lexives.pokedex.state.DataState.Error
import com.lexives.pokedex.state.DataState.Loading
import com.lexives.pokedex.state.DataState.Success
import com.lexives.pokedex.viewModel.PokemonListViewModel
import kotlinx.coroutines.flow.distinctUntilChanged

val BACKGROUND_COLOR = Color(0xFF2B2B2C)

@Composable
fun PokemonListScreen() {
    val viewModel = hiltViewModel<PokemonListViewModel>()
    val viewState = viewModel.viewState.collectAsState()

    PokemonListScreenContent(
        state = viewState.value.pokemonListState,
        onScrolledToLastItem = viewModel::fetchMorePokemon
    )
}

@Composable
fun PokemonListScreenContent(
    state: DataState<List<DataState<Pokemon>>>,
    onScrolledToLastItem: () -> Unit
) {
    when (state) {
        is Loading -> {
            PokemonListSplashScreen()
        }
        is Error -> {
            PokemonListErrorScreen()
        }
        is Success -> {
            PokemonList(
                pokemonList = state.data,
                onScrolledToLastItem = onScrolledToLastItem
            )
        }
    }
}

@Composable
fun PokemonList(
    pokemonList: List<DataState<Pokemon>>,
    onScrolledToLastItem: () -> Unit = {}
) {
    val listState = rememberLazyListState()

    /** LaunchedEffect generated by AI **/
    LaunchedEffect(listState) {
        snapshotFlow {
            val layoutInfo = listState.layoutInfo
            val totalItems = layoutInfo.totalItemsCount
            val lastVisibleItem = layoutInfo.visibleItemsInfo.lastOrNull()
            totalItems > 0 && lastVisibleItem != null && lastVisibleItem.index >= totalItems - 1
        }.distinctUntilChanged()
            .collect { reachedBottom ->
                if (reachedBottom) {
                    onScrolledToLastItem()
                }
            }
    }

    LazyColumn (
        state = listState,
        verticalArrangement = Arrangement.spacedBy(12.dp),
        modifier = Modifier
            .fillMaxSize()
            .background(BACKGROUND_COLOR)
            .padding(vertical = 56.dp, horizontal = 16.dp)
    ) {
        itemsIndexed(
            items = pokemonList,
            key = { i, _ -> i }
        ) { _, pokemonState ->
            when (pokemonState) {
                is Loading -> {
                    PokemonListItemLoading()
                }

                is Error -> {
                    PokemonListItemError()
                }

                is Success -> {
                    PokemonListItem(
                        pokemon = pokemonState.data
                    )
                }
            }
        }
    }
}

/** Generated by AI **/
@Composable
fun PokemonListSplashScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFFD81E2E)),
        contentAlignment = Alignment.Center
    ) {
        AsyncImage(
            model = "https://wallpapercave.com/wp/wp8813113.jpg",
            contentDescription = null
        )
        CircularProgressIndicator(
            color = Color.White,
            modifier = Modifier.size(64.dp)
        )
    }
}

/** Generated by AI **/
@Composable
fun PokemonListErrorScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(BACKGROUND_COLOR)
            .padding(16.dp),
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = "There was an error loading Pokémon data",
            fontSize = 22.sp,
            textAlign = TextAlign.Center,
            color = Color.White
        )
    }
}

/** Previews **/

@Preview(showBackground = true)
@Composable
fun PokemonListPreview() {
    PokemonList(
        pokemonList = listOf(
            Success(
                Pokemon(
                    id = 1,
                    name = "bulbasaur",
                    sprites = PokemonSprites(),
                    firstType = PokemonType(
                        name = "grass"
                    ),
                    secondType = PokemonType(
                        name = "poison"
                    )
                )
            ),
            Success(
                Pokemon(
                    id = 4,
                    name = "charmander",
                    sprites = PokemonSprites(),
                    firstType = PokemonType(
                        name = "fire"
                    )
                )
            ),
            Success(
                Pokemon(
                    id = 7,
                    name = "squirtle",
                    sprites = PokemonSprites(),
                    firstType = PokemonType(
                        name = "water"
                    )
                )
            )
        )
    )
}

@Preview(showBackground = true)
@Composable
fun PokemonListSplashPreview() {
    PokemonListSplashScreen()
}

@Preview(showBackground = true)
@Composable
fun PokemonListErrorPreview() {
    PokemonListErrorScreen()
}
