package com.lexives.pokedex.view

import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.lexives.pokedex.domain.Pokemon
import com.lexives.pokedex.domain.PokemonSprites
import com.lexives.pokedex.domain.PokemonType

val CONTENT_PADDING = 12.dp

@Composable
fun PokemonListItem(
    pokemon: Pokemon,
    modifier: Modifier = Modifier
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(4.dp),
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(8.dp))
            .background(Color(0xFF5A6F85))
            .padding(CONTENT_PADDING)
    ) {
        PokemonSprite(
            sprites = pokemon.sprites,
            modifier = Modifier.padding(end = 8.dp)
        )
        Text(
            text = pokemon.name,
            color = Color.White,
            fontSize = 24.sp,
            modifier = Modifier.weight(1f)
        )
        TypeChip(type = pokemon.firstType)
        pokemon.secondType?.let {
            TypeChip(type = it)
        }
    }
}

/** Generated by AI **/
@Composable
fun PokemonListItemLoading(
    modifier: Modifier = Modifier
) {
    val transition = rememberInfiniteTransition(label = "shimmerTransition")
    val translateAnim = transition.animateFloat(
        initialValue = 0f,
        targetValue = 1000f,
        animationSpec = infiniteRepeatable(
            animation = tween(durationMillis = 1200, easing = LinearEasing),
            repeatMode = RepeatMode.Restart
        ),
        label = "shimmerTranslate"
    )

    val shimmerColors = listOf(
        Color(0xFF5A6F85).copy(alpha = 0.6f),
        Color(0xFF7A93AF).copy(alpha = 0.9f),
        Color(0xFF5A6F85).copy(alpha = 0.6f)
    )

    val brush = Brush.linearGradient(
        colors = shimmerColors,
        start = Offset.Zero,
        end = Offset(x = translateAnim.value, y = translateAnim.value)
    )

    Row(
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(4.dp),
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(8.dp))
            .background(brush)
            .padding(CONTENT_PADDING)
    ) {
        Box(
            modifier = Modifier
                .size(SPRITE_SIZE)
                .clip(CircleShape)
                .background(Color.White.copy(alpha = 0.3f))
        )
        Box(
            modifier = Modifier
                .weight(1f)
                .height(36.dp)
                .padding(start = 8.dp)
                .clip(RoundedCornerShape(4.dp))
                .background(Color.White.copy(alpha = 0.3f))
        )
    }
}

/** Generated by AI **/
@Composable
fun PokemonListItemError(
    modifier: Modifier = Modifier
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(8.dp))
            .background(Color(0xFF5A6F85))
            .padding(vertical = 36.dp, horizontal = CONTENT_PADDING)
    ) {
        Text(
            text = "Failed to load Pokémon data",
            color = Color.White.copy(alpha = 0.8f),
            fontSize = 16.sp,
            fontStyle = FontStyle.Italic,
        )
    }
}

/** Previews **/

@Preview(showBackground = true)
@Composable
fun PokemonListItemPreview() {
    PokemonListItem(
        pokemon = Pokemon(
            id = 1,
            name = "bulbasaur",
            sprites = PokemonSprites(),
            firstType = PokemonType(
                name = "grass"
            ),
            secondType = PokemonType(
                name = "poison"
            )
        )
    )
}

@Preview(showBackground = true)
@Composable
fun PokemonListItemLoadingPreview() {
    PokemonListItemLoading()
}

@Preview(showBackground = true)
@Composable
fun PokemonListItemErrorPreview() {
    PokemonListItemError()
}
