package com.lexives.pokedex.view

import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.core.tween
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.slideOutHorizontally
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import coil3.compose.AsyncImage
import com.lexives.pokedex.domain.Pokemon
import com.lexives.pokedex.domain.PokemonSprites
import com.lexives.pokedex.domain.PokemonType
import com.lexives.pokedex.state.DataState
import com.lexives.pokedex.state.DataState.Error
import com.lexives.pokedex.state.DataState.Loading
import com.lexives.pokedex.state.DataState.Success
import com.lexives.pokedex.viewModel.PokemonListViewModel
import com.lexives.pokedex.viewModel.PokemonListViewModel.Companion.ViewState

@Composable
fun PokemonListScreen() {
    val viewModel = hiltViewModel<PokemonListViewModel>()
    val viewState = viewModel.viewState.collectAsState()

    PokemonListScreenContent(viewState.value)
}

@Composable
fun PokemonListScreenContent(
    viewState: ViewState
) {
    /** Animation generated by AI **/
    AnimatedContent(
        targetState = viewState.pokemonListState,
        transitionSpec = {
            if (initialState is Loading) {
                fadeIn(animationSpec = tween(300)) togetherWith
                        slideOutHorizontally(animationSpec = tween(400)) { width -> -width } +
                        fadeOut(animationSpec = tween(300))
            } else {
                fadeIn(animationSpec = tween(300)) togetherWith
                        fadeOut(animationSpec = tween(300))
            }
        },
        label = "pokemonListScreenTransition"
    ) { state ->
        when (state) {
            is Loading -> {
                PokemonListSplashScreen()
            }
            is Error -> {
                PokemonListErrorScreen()
            }
            is Success -> {
                PokemonList(state.data)
            }
        }
    }
}

/** Generated by AI **/
@Composable
fun PokemonListSplashScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFFE83333)),
        contentAlignment = Alignment.Center
    ) {
        AsyncImage(
            model = "https://wallpapercave.com/wp/wp8813113.jpg",
            contentDescription = null,
            contentScale = ContentScale.FillBounds,
            modifier = Modifier.fillMaxSize()
        )
        CircularProgressIndicator(
            color = Color.White,
            modifier = Modifier.size(64.dp)
        )
    }
}

/** Generated by AI **/
@Composable
fun PokemonListErrorScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = "There was an error loading Pokémon data",
            fontSize = 22.sp,
            textAlign = TextAlign.Center,
            color = Color.DarkGray
        )
    }
}

@Composable
fun PokemonList(
    pokemonList: List<DataState<Pokemon>>
) {
    LazyColumn (
        verticalArrangement = Arrangement.spacedBy(12.dp),
        modifier = Modifier
            .fillMaxSize()
            .padding(vertical = 56.dp, horizontal = 16.dp)
    ) {
        pokemonList.forEachIndexed { i, pokemonState ->
            item(key = i) {
                when (pokemonState) {
                    is Loading -> {
                        PokemonListItemLoading()
                    }

                    is Error -> {
                        PokemonListItemError()
                    }

                    is Success -> {
                        PokemonListItem(
                            pokemon = pokemonState.data
                        )
                    }
                }
            }
        }
    }
}

/** Previews **/

@Preview(showBackground = true)
@Composable
fun PokemonListPreview() {
    PokemonList(
        pokemonList = listOf(
            Success(
                Pokemon(
                    id = 1,
                    name = "bulbasaur",
                    sprites = PokemonSprites(),
                    firstType = PokemonType(
                        name = "grass"
                    ),
                    secondType = PokemonType(
                        name = "poison"
                    )
                )
            ),
            Success(
                Pokemon(
                    id = 4,
                    name = "charmander",
                    sprites = PokemonSprites(),
                    firstType = PokemonType(
                        name = "fire"
                    )
                )
            ),
            Success(
                Pokemon(
                    id = 7,
                    name = "squirtle",
                    sprites = PokemonSprites(),
                    firstType = PokemonType(
                        name = "water"
                    )
                )
            )
        )
    )
}

@Preview(showBackground = true)
@Composable
fun PokemonListSplashPreview() {
    PokemonListSplashScreen()
}

@Preview(showBackground = true)
@Composable
fun PokemonListErrorPreview() {
    PokemonListErrorScreen()
}
